=== yagolscpt/Ejemplos-Layaout-y-Bootstrap/Layaout y Bootstrap/ejercicio1tercera.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.examen.net"
           xmlns:disc="https://www.examen.net"
           elementFormDefault="qualified">

    <xs:element name="Oferta" type="disc:tipooferta"/>

    <xs:complexType  name="tipooferta" >
        <xs:sequence>
            <xs:element type="disc:tipocd" name="cd" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipocd">
        <xs:sequence>
            <xs:element type="xs:string" name="titulo"/>
            <xs:element type="xs:string" name="artista"/>
            <xs:element type="xs:string" name="pais"/>
            <xs:element type="xs:string" name="compañiadiscografica"/>
            <xs:element type="xs:string" name="precio"/>
            <xs:element type="xs:string" name="añopublicacion"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== yagolscpt/Ejemplos-Layaout-y-Bootstrap/Layaout y Bootstrap/ejercicio1tercera.xml
<?xml version="1.0" encoding="UTF-8"?>
<disc:Oferta  xmlns:disc="https://www.examen.net"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://www.examen.net ejercicio1tercera.xsd">
    <disc:cd>
        <disc:titulo>Still got the blues</disc:titulo>
        <disc:artista>Gary Moore</disc:artista>
        <disc:pais>UK</disc:pais>
        <disc:compañiadiscografica>Virgin records</disc:compañiadiscografica>
        <disc:precio>10.20</disc:precio>
        <disc:añopublicacion>1990</disc:añopublicacion>
    </disc:cd>
    <disc:cd>
        <disc:titulo>One nigth only</disc:titulo>
        <disc:artista>Bee Gees</disc:artista>
        <disc:pais>UK</disc:pais>
        <disc:compañiadiscografica>Polydor</disc:compañiadiscografica>
        <disc:precio>10.90</disc:precio>
        <disc:añopublicacion>1998</disc:añopublicacion>
    </disc:cd>
    <disc:cd>
        <disc:titulo>When a man loves a woman</disc:titulo>
        <disc:artista>Percy Sledge</disc:artista>
        <disc:pais>USA</disc:pais>
        <disc:compañiadiscografica>Atlantic</disc:compañiadiscografica>
        <disc:precio>8.70</disc:precio>
        <disc:añopublicacion>1987</disc:añopublicacion>
    </disc:cd>
    <disc:cd>
        <disc:titulo>Big Willie style</disc:titulo>
        <disc:artista>Will Smith</disc:artista>
        <disc:pais>USA</disc:pais>
        <disc:compañiadiscografica>Columbia</disc:compañiadiscografica>
        <disc:precio>9.90</disc:precio>
        <disc:añopublicacion>1997</disc:añopublicacion>
    </disc:cd>
    <disc:cd>
        <disc:titulo>La Cancion de Juan Perro</disc:titulo>
        <disc:artista>Radio Futura</disc:artista>
        <disc:pais>España</disc:pais>
        <disc:compañiadiscografica>Sony Music-Ariola</disc:compañiadiscografica>
        <disc:precio>9.90</disc:precio>
        <disc:añopublicacion>1987</disc:añopublicacion>
    </disc:cd>
    <disc:cd>
        <disc:titulo>The dock of the bay</disc:titulo>
        <disc:artista>Otis Redding</disc:artista>
        <disc:pais>USA</disc:pais>
        <disc:compañiadiscografica>Atlantic</disc:compañiadiscografica>
        <disc:precio>7.90</disc:precio>
        <disc:añopublicacion>1987</disc:añopublicacion>
    </disc:cd>
</disc:Oferta>
