=== yagolscpt/Ejemplos-Layaout-y-Bootstrap/Layaout y Bootstrap/videoclub.xsd
<?xml version="1.0" encoding="UTF-8"?>


<!-- Versión con referencias (ref)
por tanto es necesario añadir como atributo al esquema
la linea que explica el espacio de nombres
xlmns:fac="http://www.empresa.com/"
((si no hubiese ref no seria necesario)) -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.empresa.com/"
           xmlns:fac="http://www.empresa.com/"
           elementFormDefault="qualified">
    <!-- ====== ELEMENTO facturas ====== -->
    <xs:element name="facturas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fac:factura" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- ====== ELEMENTO factura ====== -->
    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fac:datos_cliente" minOccurs="1" maxOccurs="1" />
                <xs:element ref="fac:datos_factura" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- ====== ELEMENTO datos_cliente ====== -->
    <xs:element name="datos_cliente">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fac:nombre" minOccurs="1" maxOccurs="1" />
                <xs:element ref="fac:apellido" minOccurs="2" maxOccurs="2" />
                <xs:element ref="fac:dni" minOccurs="1" maxOccurs="1" />
                <xs:element ref="fac:tfno" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
            <xs:attribute name="ident" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
    <!-- ====== ELEMENTO nombre ====== -->
    <xs:element name="nombre" type="xs:string" />
    <!-- ====== ELEMENTO apellido ====== -->
    <xs:element name="apellido" type="xs:string" />
    <!-- ====== ELEMENTO dni ====== -->
    <xs:element name="dni">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{8}[A-Z]" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <!-- ====== ELEMENTO tfno ====== -->
    <xs:element name="tfno">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{9}" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <!-- ====== ELEMENTO datos_factura ====== -->
    <xs:element name="datos_factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fac:resguardo" minOccurs="1" maxOccurs="1" />
                <xs:sequence>
                    <xs:element ref="fac:alquileres" minOccurs="1" maxOccurs="1" />
                </xs:sequence>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- ====== ELEMENTO resguardo ====== -->
    <xs:element name="resguardo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fac:forma_pago" minOccurs="1" maxOccurs="1" />
                <xs:element ref="fac:importe_total" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- ====== ELEMENTO forma_pago ====== -->
    <xs:element name="forma_pago" type="xs:string" />
    <!-- ====== ELEMENTO importe_total ====== -->
    <xs:element name="importe_total" type="xs:float" />
    <!-- ====== ELEMENTO alquileres ====== -->
    <xs:element name="alquileres">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fac:fecha" minOccurs="1" maxOccurs="1" />
                <xs:element ref="fac:peliculas" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- ====== ELEMENTO fecha ====== -->
    <xs:element name="fecha" type="xs:date" />
    <!-- ====== ELEMENTO peliculas ====== -->
    <xs:element name="peliculas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fac:pelicula" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- ====== ELEMENTO pelicula ====== -->
    <xs:element name="pelicula">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fac:titulo" minOccurs="1" maxOccurs="1" />
                <xs:element ref="fac:genero" minOccurs="1" maxOccurs="1" />
                <xs:element ref="fac:duracion" minOccurs="1" maxOccurs="1" />
                <xs:element ref="fac:actores" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
            <xs:attribute name="id_pelicula" type="xs:string" use="required" />
            <xs:attribute name="valoracion" type="xs:string" />
        </xs:complexType>
    </xs:element>
    <!-- ====== ELEMENTO titulo ====== -->
    <xs:element name="titulo" type="xs:string" />
    <!-- ====== ELEMENTO genero ====== -->
    <xs:element name="genero" type="xs:string" />
    <!-- ====== ELEMENTO duracion ====== -->
    <xs:element name="duracion" type="xs:positiveInteger" />
    <!-- ====== ELEMENTO actores ====== -->
    <xs:element name="actores">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fac:actor" minOccurs="3" maxOccurs="3" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- ====== ELEMENTO actor ====== -->
    <xs:element name="actor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fac:nombre" minOccurs="1" maxOccurs="1" />
                <xs:element ref="fac:apellido" minOccurs="2" maxOccurs="2" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== yagolscpt/Ejemplos-Layaout-y-Bootstrap/Layaout y Bootstrap/videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
(CUANDO MARCA COMO ERROR EL ESPACIO DE NOMBRES
SOLO TENEMOS QUE DARLE EN LA OPCIONIGNORA RECURSO EXTERNO)
-->
<fac:facturas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="videoclub.xsd http://www.empresa.com/"
              xmlns:fac="http://www.empresa.com/">
    <fac:factura>
        <fac:datos_cliente ident="abcd">
            <fac:nombre>Juan</fac:nombre>
            <fac:apellido>López</fac:apellido>
            <fac:apellido>Jiménez</fac:apellido>
            <fac:dni>11111111N</fac:dni>
            <fac:tfno>123456789</fac:tfno>
        </fac:datos_cliente>
        <fac:datos_factura>
            <fac:resguardo>
                <fac:forma_pago>
                    Efectivo
                </fac:forma_pago>
                <fac:importe_total>
                    1256325.23
                </fac:importe_total>
            </fac:resguardo>
            <fac:alquileres>
                <fac:fecha>2010-12-25</fac:fecha>
                <fac:peliculas>
                    <fac:pelicula id_pelicula="ABC" valoracion="buena">
                        <fac:titulo>El retorno del Jedi</fac:titulo>
                        <fac:genero>Espacio</fac:genero>
                        <fac:duracion>125</fac:duracion>
                        <fac:actores>
                            <fac:actor>
                                <fac:nombre>Juan</fac:nombre>
                                <fac:apellido>Pardo</fac:apellido>
                                <fac:apellido>López</fac:apellido>
                            </fac:actor>
                            <fac:actor>
                                <fac:nombre>Manuel</fac:nombre>
                                <fac:apellido>Bandera</fac:apellido>
                                <fac:apellido>Garrido</fac:apellido>
                            </fac:actor>
                            <fac:actor>
                                <fac:nombre>Luis</fac:nombre>
                                <fac:apellido>González</fac:apellido>
                                <fac:apellido>Romero</fac:apellido>
                            </fac:actor>
                        </fac:actores>
                    </fac:pelicula>
                </fac:peliculas>
            </fac:alquileres>
        </fac:datos_factura>
    </fac:factura>
</fac:facturas>
