=== yagolscpt/Ejemplos-Layaout-y-Bootstrap/Layaout y Bootstrap/vuelos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:element name="panelvuelos" type="tpanelvuelos"/>

  <xs:complexType name="tvuelo">
    <xs:sequence>
      <xs:element type="tdiario" name="diario" default=" " />
      <xs:element type="xs:string" name="origen"/>
      <xs:element type="xs:string" name="destino"/>
      <xs:element type="xs:string" name="horasalida"/>
      <xs:element type="xs:string" name="horallegada"/>
      <xs:element type="estadovuelo" name="estado" default="E"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="codigo" use="optional"/>
    
  </xs:complexType>
  <xs:complexType name="tpanelvuelos">
    <xs:sequence>
      <xs:element type="tvuelo" name="vuelo" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="tdiario">
    <xs:restriction base="xs:string">
     <xs:enumeration value="si"/>
      <xs:enumeration value=" "></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="estadovuelo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="C"/>
       <xs:enumeration value="E"/>
      <xs:enumeration value="R"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== yagolscpt/Ejemplos-Layaout-y-Bootstrap/Layaout y Bootstrap/vuelos.xml
<?xml version="1.0" encoding="UTF-8"?>
<panelvuelos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="vuelos.xsd">
    <vuelo codigo="v22" >

       <diario> </diario>
        <origen>New york</origen>
        <destino>Chicago</destino>
        <horasalida>10:15</horasalida>
       <horallegada>12:15</horallegada>
       <estado>C</estado>

    </vuelo>

    <vuelo codigo="V23">

        <diario> </diario>
        <origen>New York</origen>
        <destino>Miami</destino>
        <horasalida>9:30</horasalida>
        <horallegada>11:30</horallegada>
        <estado>C</estado>
    </vuelo>


</panelvuelos>
